# Generated by Django 5.0.1 on 2024-01-31 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oprole',
            old_name='players',
            new_name='player',
        ),
    ]
