# Generated by Django 5.0.1 on 2024-01-31 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_players_oprole_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='op_slottingstartdatetime',
        ),
    ]
