# Generated by Django 5.0.1 on 2024-01-30 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Yhteisö')),
                ('shortname', models.CharField(blank=True, max_length=30, null=True, verbose_name='Lyhyt nimi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Kuvaus')),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rankname', models.CharField(blank=True, max_length=30, null=True, verbose_name='Arvo')),
                ('rankappr', models.CharField(blank=True, max_length=20, null=True, verbose_name='Lyhenne')),
                ('rankvalue', models.IntegerField(blank=True, choices=[(20, 'Alokas'), (40, 'Miehistö'), (60, 'Aliupseeri'), (80, 'Upseeri'), (200, 'Kenraali')], verbose_name='Luokka')),
            ],
        ),
        migrations.CreateModel(
            name='VRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rankname', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nimike')),
                ('rankappr', models.CharField(blank=True, max_length=20, null=True, verbose_name='Lyhenne')),
                ('rankvalue', models.IntegerField(blank=True, choices=[(20, 'Alokas'), (40, 'Miehistö'), (60, 'Aliupseeri'), (80, 'Upseeri'), (200, 'Kenraali')], verbose_name='Luokka')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30, verbose_name='Nimimerkki')),
                ('firstname', models.CharField(blank=True, max_length=30, null=True, verbose_name='Etunimi')),
                ('lastname', models.CharField(blank=True, max_length=30, null=True, verbose_name='Sukunimi')),
                ('active', models.BooleanField(default=True)),
                ('community', models.ManyToManyField(to='communities.community')),
                ('rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='communities.rank', verbose_name='Arvo')),
                ('vrank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='communities.vrank', verbose_name='Virt.arvo')),
            ],
        ),
    ]
